import { Logo } from "@/components/ui/logo";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { QueryProvider } from "@/shared/ui/query-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ru"
			data-theme="dark"
			className={cn(
				"h-full",
				"antialiased",
				geistSans.variable,
				geistMono.variable,
				"font-sans",
				outfit.variable,
			)}
		>
			<body className="min-h-full flex flex-col">
				<div>
					<Logo variant="cyrillic" />
					<Logo variant="latin" />
				</div>
				<QueryProvider>
					<TooltipProvider>{children}</TooltipProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
